name: newsapp
description: A simple news app using NewsAPI.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.6
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
