name: newsapp
description: A simple news app using NewsAPI.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: any  # Allow latest version
  http: any  # Allow latest version
  url_launcher: any  # Allow latest version

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.png
