name: news_app
description: A simple news aggregator app.
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^0.13.4
  url_launcher: ^6.1.10
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder.png
